_BASE_: "../DECOLA_PHASE1_MarineDet_CLIP_SwinB_4x_inter.yaml"
MODEL:
  WEIGHTS: "weights/DECOLA_PHASE1_MarineDet_CLIP_SwinB_4x_inter.pth"
  DECOLA: 
    PROB_A_OBJECT: 1.0
    ORACLE_EVALUATION: False 
    TEST_CLASS_CONDITIONED: False 
    ZS_WEIGHT_PATH: "datasets/metadata/lvis_v1_clip_a+cname.npy"
    TEST_SCORE_THRESHOLD: 0.0
  DETR:
    NUM_OBJECT_QUERIES: 300
    NUM_CLASSES: 482 # lvis eval
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
DATASETS:
  TEST: ("marine_inter_val_seen", )
TEST:
  DETECTIONS_PER_IMAGE: 9999
