_BASE_: "DECOLA_PHASE1_MarineDet_CLIP_SwinB_4x.yaml"
MODEL:
  WEIGHTS: "weights/DECOLA_PHASE1_MarineDet_CLIP_SwinB_4x.pth" 
  DECOLA:
    WEAK_LOSS_PSEUDO_TYPE: 'max-score'
    USE_PSEUDO_LABELING_FOR_WEAK_LOSS: True 
    PROB_A_OBJECT: 1.0
    TEST_CLASS_CONDITIONED: False 
    ORACLE_EVALUATION: False 
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: [480, 800]
DATASETS:
  TRAIN: ("marine_train_all","marine_pseduo")
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 4]
  USE_RFS: [True, True]
  DATASET_MIN_SIZES: [[480, 800], [240, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'box']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True 
